[variables]
main_domain   = "${domain}"
puid          = "${PUID:-1000}"
pgid          = "${PGID:-1000}"
incoming_port = "${INCOMING_PORT:-50000}"
dht_port      = "${DHT_PORT:-6881}"

[config]
# Dokploy will route this domain to the container's internal port 8080
[[config.domains]]
serviceName = "rutorrent"
port        = 8080
host        = "${main_domain}"

[config.env]
PUID = "${puid}"
PGID = "${pgid}"
INCOMING_PORT = "${incoming_port}"
DHT_PORT      = "${dht_port}"

[[config.mounts]]
type   = "volume"
source = "rutorrent-data"
target = "/data"

[[config.mounts]]
type   = "volume"
source = "rutorrent-downloads"
target = "/downloads"

[[config.mounts]]
type   = "volume"
source = "rutorrent-passwd"
target = "/passwd"
