[variables]
main_domain   = "${domain}"
api_domain    = "${domain}"
db_password   = "${password}"
redis_password = "${password}"
cookie_secret = "${base64:32}"

[config]
# ---- Mount helper files for ClickHouse ----
[[config.mounts]]
filePath = "clickhouse/clickhouse-config.xml"
content = """
<clickhouse>
  <logger>
    <level>warning</level>
    <console>true</console>
  </logger>
  <keep_alive_timeout>10</keep_alive_timeout>
  <!-- Reduce logging noise -->
  <query_thread_log remove="remove"/>
  <query_log remove="remove"/>
  <text_log remove="remove"/>
  <trace_log remove="remove"/>
  <metric_log remove="remove"/>
  <asynchronous_metric_log remove="remove"/>
  <session_log remove="remove"/>
  <part_log remove="remove"/>

  <listen_host>0.0.0.0</listen_host>
  <interserver_listen_host>0.0.0.0</interserver_listen_host>
  <!-- IMPORTANT: match the service name 'op-ch' -->
  <interserver_http_host>op-ch</interserver_http_host>

  <!-- Disable cgroup memory observer -->
  <cgroups_memory_usage_observer_wait_time>0</cgroups_memory_usage_observer_wait_time>

  <!-- Legacy macros kept for compat -->
  <macros>
    <shard>1</shard>
    <replica>replica1</replica>
    <cluster>openpanel_cluster</cluster>
  </macros>
</clickhouse>
"""

[[config.mounts]]
filePath = "clickhouse/clickhouse-user-config.xml"
content = """
<clickhouse>
  <profiles>
    <default>
      <log_queries>0</log_queries>
      <log_query_threads>0</log_query_threads>
    </default>
  </profiles>
</clickhouse>
"""

[[config.mounts]]
filePath = "clickhouse/init-db.sql"
content = """
CREATE DATABASE IF NOT EXISTS openpanel;
"""

# ---- Domains (no ports exposed; Dokploy routes to internal 3000) ----
[[config.domains]]
serviceName = "op-dashboard"
port = 3000
host = "${main_domain}"

[[config.domains]]
serviceName = "op-api"
port = 3000
host = "${api_domain}"

# ---- Environment injected into the stack ----
[config.env]
# Public FQDNs used by the apps
SERVICE_FQDN_OPDASHBOARD = "http://${main_domain}"
SERVICE_FQDN_OPAPI       = "http://${api_domain}"

# DB / KV credentials
OPENPANEL_POSTGRES_DB   = "openpanel-db"
SERVICE_USER_POSTGRES   = "openpanel"
SERVICE_PASSWORD_POSTGRES = "${db_password}"
SERVICE_PASSWORD_REDIS    = "${redis_password}"

# App secrets
SERVICE_BASE64_COOKIESECRET = "${cookie_secret}"

# Scaling knobs
OP_WORKER_REPLICAS = "1"

# Optional email + registration flags
RESEND_API_KEY = ""
OPENPANEL_ALLOW_REGISTRATION = "true"
OPENPANEL_ALLOW_INVITATION   = "true"
