version: "3.8"
services:
  typesense:
    image: typesense/typesense:29.0
    restart: unless-stopped
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_ENABLE_CORS=${TYPESENSE_ENABLE_CORS}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense-data:/data

volumes:
  typesense-data:
