[variables]
main_domain = "${domain}"
postgres_password = "${password:32}"
jwt_secret = "${password:64}"

[config]
[[config.domains]]
serviceName = "tianji"
port = 12345
host = "${main_domain}"

[config.env]
# Database
POSTGRES_DB = "tianji"
POSTGRES_USER = "tianji"
POSTGRES_PASSWORD = "${postgres_password}"
DATABASE_URL = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"

# Auth & Security
JWT_SECRET = "${jwt_secret}"
JWT_ISSUER = "tianji.msgbyte.com"
JWT_AUDIENCE = "msgbyte.com"

# Features
ALLOW_REGISTER = "false"
ALLOW_OPENAPI = "true"

# Optional tracking / analytics IDs
WEBSITE_ID = ""

# Optional ClickHouse integration
CLICKHOUSE_URL = ""
CLICKHOUSE_USER = ""
CLICKHOUSE_PASSWORD = ""
CLICKHOUSE_DATABASE = ""

[[config.mounts]]
