[variables]
main_domain = "${domain}"
db_password = "${password:24}"
db_root_password = "${password:24}"

[config]
[[config.domains]]
serviceName = "gitea"
port = 3000
host = "${main_domain}"

[config.env]
USER_UID = "1000"
USER_GID = "1000"
GITEA__database__DB_TYPE = "mysql"
GITEA__database__HOST = "mysql:3306"
GITEA__database__NAME = "gitea"
GITEA__database__USER = "gitea"
GITEA__database__PASSWD = "${db_password}"
GITEA_DB_PASSWORD = "${db_password}"
MYSQL_ROOT_PASSWORD = "${db_root_password}"

[[config.mounts]]